apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mservice
  namespace: rabbitmq-setup
spec:
  template:
    metadata:
      labels:
        app: mservice
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containers:
        - image: christinedia/routing:new                #routing:final      
          env:
            - name: REDIS_URL
              value: "my-redis-master.rabbitmq-setup.svc.cluster.local:6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-redis
                  key: redis-password
            - name: NUM_SERVICES
              value: "3"
            - name: RABBITMQ_URL
              value: "http://rabbitmq.rabbitmq-setup.svc.cluster.local:15672/api/queues"
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: password
            - name: CHECK_INTERVAL
              value: "1000"
            - name: SERVICE1_INITIAL_CURR_WEIGHT
              value: "23"
            - name: SERVICE1_INITIAL_EMPTYQ_WEIGHT
              value: "23"
            - name: SERVICE1_RAW_ADMISSION_RATE
              value: "23"
            - name: SERVICE1_ALPHA
              value: "3"
            - name: SERVICE1_BETA
              value: "0.5"
            - name: SERVICE2_INITIAL_CURR_WEIGHT
              value: "27"
            - name: SERVICE2_INITIAL_EMPTYQ_WEIGHT
              value: "27"
            - name: SERVICE2_RAW_ADMISSION_RATE
              value: "27"
            - name: SERVICE2_ALPHA
              value: "4"
            - name: SERVICE2_BETA
              value: "0.5"
            - name: SERVICE3_INITIAL_CURR_WEIGHT
              value: "50"
            - name: SERVICE3_INITIAL_EMPTYQ_WEIGHT
              value: "50"
            - name: SERVICE3_RAW_ADMISSION_RATE
              value: "50"
            - name: SERVICE3_ALPHA
              value: "7"
            - name: SERVICE3_BETA
              value: "0.5"
            - name: MAX_ADMISSION_RATE
              value: "100"

          readinessProbe:
            successThreshold: 1
            tcpSocket:
              port: 8080
          ports:
            - containerPort: 8080
            
