apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: consumer-service-3
  namespace: rabbitmq-setup
spec:
  template:
    metadata:
      labels:
        app: event-display
        service: consumer-service-3
      annotations:
        #  autoscaling.knative.dev/target-utilization-percentage: "60"
          #autoscaling.knative.dev/minScale: "2"
          #       autoscaling.knative.dev/maxScale: "2"
          #  autoscaling.knative.dev/metric: "concurrency"
          # autoscaling.knative.dev/target: "1"
      #   autoscaling.knative.dev/scale-to-zero: "true"
      #   autoscaling.knative.dev/scale-up-rate: "10.0"
      #   autoscaling.knative.dev/panic-window: "10s"
      #   autoscaling.knative.dev/panic-threshold-percentage: "200"  # More aggressive scaling
    spec:
      containers:
        - image: christinedia/event-consumer:display3   #third
          env:
            - name: SERVICE_NAME
              value: "consumer-service-3"
            - name: QUEUE_SIZE
              value: "5"
            - name: NUM_WORKERS
              value: "2"
          resources:
            limits:
              cpu: "2000m"       # 4 CPU cores
              memory: "5Gi"    # 2.2 GiB
            requests:
              cpu: "1500m"        # 2 CPU cores
              memory: "3.5Gi"    # 1.7 GiB

  traffic:
    - latestRevision: true
      percent: 100
