apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: service1
  namespace: rabbitmq-setup
spec:
  template:
    metadata:
      labels:
        app: event-display
        version: v1
      # annotations:
      #   autoscaling.knative.dev/minScale: "1"
      #   autoscaling.knative.dev/maxScale: "10"
      #   autoscaling.knative.dev/metric: "rps"
      #   autoscaling.knative.dev/target: "10"
      #   autoscaling.knative.dev/scale-to-zero: "true"
      #   autoscaling.knative.dev/scale-up-rate: "10.0"
      #   autoscaling.knative.dev/panic-window: "10s"
      #   autoscaling.knative.dev/panic-threshold-percentage: "200"  # More aggressive scaling
    spec:
      containers:
        - image: christinedia/event-consumer:opencv4   #third
          env:
            - name: QUEUE_SIZE
              value: "1"
          resources:
            limits:
              cpu: "4000m"       # 10 CPU cores
              memory: "2200Mi"    # 2.2 GiB
            requests:
              cpu: "2000m"        # 8 CPU cores
              memory: "1700Mi"    # 1.7 GiB
  traffic:
    - latestRevision: true
      percent: 100
