apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: service2
  namespace: rabbitmq-setup
spec:
  template:
    metadata:
      labels:
        app: event-display
        version: v2
      annotations:
      #   autoscaling.knative.dev/minScale: "1"
          autoscaling.knative.dev/maxScale: "3"
          autoscaling.knative.dev/metric: "concurrency"
          autoscaling.knative.dev/target: "1"
      #   autoscaling.knative.dev/scale-to-zero: "true"
      #   autoscaling.knative.dev/scale-up-rate: "10.0"
      #   autoscaling.knative.dev/panic-window: "10s"
      #   autoscaling.knative.dev/panic-threshold-percentage: "200"  # More aggressive scaling
    spec:
      containerConcurrency: 2
      containers:
        - image: christinedia/event-consumer:display #opencv4   #third
          env:
            - name: QUEUE_SIZE
              value: "1"
          resources:
            limits:
              cpu: "4000m"       # 4 CPU cores
              memory: "3072Mi"    # 2.2 GiB
            requests:
              cpu: "500m"        # 2 CPU cores
              memory: "1024Mi"    # 1.7 GiB
  traffic:
    - latestRevision: true
      percent: 100
