apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: service1
  namespace: rabbitmq-setup
spec:
  template:
    metadata:
      labels:
        app: event-display
        version: v1
      annotations:
      #   autoscaling.knative.dev/minScale: "1"
          autoscaling.knative.dev/maxScale: "10"
          autoscaling.knative.dev/metric: "concurrency"
            # autoscaling.knative.dev/target-utilization-percentage: "60"
          autoscaling.knative.dev/target: "0.5"
      #   autoscaling.knative.dev/scale-to-zero: "true"
      #   autoscaling.knative.dev/scale-up-rate: "10.0"
      #   autoscaling.knative.dev/panic-window: "10s"
      #   autoscaling.knative.dev/panic-threshold-percentage: "200"  # More aggressive scaling
    spec:
      containerConcurrency: 1
      containers:
        - image: christinedia/event-consumer:display #opencv4   #third
          env:
            - name: QUEUE_SIZE
              value: "2"
          resources:
            limits:
              cpu: "1000m"       # 4 CPU cores
              memory: "2048Mi"    # 2.2 GiB
            requests:
              cpu: "1000m"        # 2 CPU cores
              memory: "2048Mi"    # 1.7 GiB
  traffic:
    - latestRevision: true
      percent: 100
