apiVersion: v1
kind: Service
metadata:
  name: service-metrics
  namespace: rabbitmq-setup
  labels:
    app: consumer-metrics
spec:
  selector:
    app: event-display
  ports:
    - protocol: TCP
      port: 9095
      targetPort: 9095
      name: metrics
  type: ClusterIP
