apiVersion: v1
kind: Service
metadata:
  name: service1-metrics
  namespace: rabbitmq-setup
  labels:
    app: consumer-metrics
spec:
  selector:
    service: service1
    app: event-display
  ports:
    - protocol: TCP
      port: 9095
      targetPort: 9095
      name: metrics
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: service2-metrics
  namespace: rabbitmq-setup
  labels:
    app: consumer-metrics
spec:
  selector:
    service: service2
    app: event-display
  ports:
    - protocol: TCP
      port: 9095
      targetPort: 9095
      name: metrics
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: service3-metrics
  namespace: rabbitmq-setup
  labels:
    app: consumer-metrics
spec:
  selector:
    service: service3
    app: event-display
  ports:
    - protocol: TCP
      port: 9095
      targetPort: 9095
      name: metrics
  type: ClusterIP
