apiVersion: v1
kind: Service
metadata:
  name: mservice-metrics
  namespace: rabbitmq-setup
  labels:
    app: mservice-metrics-2112
spec:
  selector:
    app: mservice
  ports:
    - protocol: TCP
      port: 9095
      targetPort: 9095
      name: metrics
  type: ClusterIP

