apiVersion: v1
kind: Service
metadata:
  name: event-trigger-dispatcher
  namespace: rabbitmq-setup
spec:
  selector:
    eventing.knative.dev/broker: queue
    eventing.knative.dev/brokerRole: dispatcher
  ports:
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090

