apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: event-trigger
  namespace: rabbitmq-setup
  annotations:
    rabbitmq.eventing.knative.dev/exchange: eventing-rabbitmq-source
    rabbitmq.eventing.knative.dev/routingKey: eventing-rabbitmq-source
    # Value must be between 1 and 1000
    # A value of 1 RabbitMQ Trigger behaves as a FIFO queue
    # Values above 1 break message ordering guarantees and can be seen as more performance oriented.
    # rabbitmq.eventing.knative.dev/parallelism: "10"
spec:
  broker: queue
  filter:
    attributes:
            type: dev.knative.rabbitmq.event
            
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: mservice
      namespace: rabbitmq-setup
