apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: consumer-service-1
  namespace: rabbitmq-setup
spec:
  template:
    metadata:
      labels:
        app: event-display
        service: consumer-service-1
      annotations:
        autoscaling.knative.dev/class: "hpa.autoscaling.knative.dev"
        autoscaling.knative.dev/metric: "cpu"
        autoscaling.knative.dev/target: "75"   # Setting the CPU target to 75%
        autoscaling.knative.dev/maxScale: "3"
    spec:
      containers:
        - image: christinedia/event-consumer:display3 #opencv4
          env:
            - name: SERVICE_NAME
              value: "consumer-service-1"
            - name: QUEUE_SIZE
              value: "2"
            - name: NUM_WORKERS
              value: "1"
          resources:
            limits:
              cpu: "1000m"       # 1 CPU core
              memory: "2048Mi"    # 2.2 GiB
            requests:
              cpu: "1000m"        # 1 CPU core
              memory: "2048Mi"    # 2 GiB
  traffic:
    - latestRevision: true
      percent: 100

---

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: consumer-service-2
  namespace: rabbitmq-setup
spec:
  template:
    metadata:
      labels:
        app: event-display
        service: consumer-service-2
      annotations:
        autoscaling.knative.dev/class: "hpa.autoscaling.knative.dev"
        autoscaling.knative.dev/metric: "cpu"
        autoscaling.knative.dev/target: "75"   # Setting the CPU target to 75%
        autoscaling.knative.dev/maxScale: "2"
    spec:
      containers:
        - image: christinedia/event-consumer:display3 #opencv4
          env:
            - name: SERVICE_NAME
              value: "consumer-service-2"
            - name: QUEUE_SIZE
              value: "4"
            - name: NUM_WORKERS
              value: "1"
          resources:
            limits:
              cpu: "1200m"       # 1.2 CPU cores
              memory: "3Gi"      # 3 GiB
            requests:
              cpu: "1000m"       # 1 CPU core
              memory: "2Gi"      # 2 GiB
  traffic:
    - latestRevision: true
      percent: 100

---

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: consumer-service-3
  namespace: rabbitmq-setup
spec:
  template:
    metadata:
      labels:
        app: event-display
        service: consumer-service-3
      annotations:
        autoscaling.knative.dev/class: "hpa.autoscaling.knative.dev"
        autoscaling.knative.dev/metric: "cpu"
        autoscaling.knative.dev/target: "75"   # Setting the CPU target to 75%
        autoscaling.knative.dev/maxScale: "2"
    spec:
      containers:
        - image: christinedia/event-consumer:display3 #opencv4
          env:
            - name: SERVICE_NAME
              value: "consumer-service-3"
            - name: QUEUE_SIZE
              value: "5"
            - name: NUM_WORKERS
              value: "2"
          resources:
            limits:
              cpu: "2000m"       # 2 CPU cores
              memory: "5Gi"      # 5 GiB
            requests:
              cpu: "1500m"       # 1.5 CPU cores
              memory: "3.5Gi"    # 3.5 GiB
  traffic:
    - latestRevision: true
      percent: 100
